# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Martin Palkovic
email: martin@palkovic.org
description: >- # this means to ignore newlines until "baseurl:"
  Howdy! I’m Martin, I'm a Data Engineer at Cooke Aquaculture. 
  I provide the organization with clean data for operational 
  and analytical reporting. I play a role in everything that entails - 
  getting the data from APIs, building and maintaining data pipelines, 
  writing tons of SQL, cleaning data, creating data models, and occasionally, 
  developing business intelligence reports. My favourite tools these days 
  are Snowflake and Python.

  My technical skills include SQL (Snowflake, SQL Server), Python, Git, Bash, 
  Docker, Boomi, Azure, Markdown, Power BI and Excel.

  In my free time I’m an avid mountain biker, DIYer and new dad. 
  I also enjoy video games, board games, hanging out with my daughter, 
  skiing and learning every day.

github_username: MartyC-137
minimal_mistakes_skin: default
search: true
future: true
timezone: America/Halifax

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Martin Palkovic"
  avatar : "/assets/images/bike_circle.jpeg"
  round-avatar: true
  bio    : "Howdy! I'm Martin. I'm a data engineer in Canada. My favourite tools are Python and Snowflake."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mpalkovic/"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/15417368/marty-c137"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MartyC-137"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/profile.php?id=100025077793438"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://martinp303.medium.com/"
    - label: "Resume"
      icon: "fab fa-fw fa-linkedin"
      url: "https://my.visualcv.com/martin-palkovic/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mpalkovic/"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/15417368/marty-c137"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MartyC-137"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/profile.php?id=100025077793438"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://martinp303.medium.com/"
    - label: "Resume"
      icon: "fab fa-fw fa-linkedin"
      url: "https://my.visualcv.com/martin-palkovic/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
